services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.1.3.23
    ports:
      - "8123:8123"   # HTTP interface
      - "9002:9002"   # Native interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: blockchain
      CLICKHOUSE_USER: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  default:
    name: blockchain_network

volumes:
  clickhouse_data:

