# Project name and description
project_name: "cherry_event_indexer"
description: "Cherry event indexing and data processing pipeline"

# Data source configuration
providers:
  my_sqd_provider:
    config:
      kind: sqd
      url: "test"
  my_hypersync_provider:
    config:
      kind: hypersync
      url: "test"

writers:
  my_local_writer:
    kind: local_parquet
    config:
      path: ""
  my_aws_wrangler_s3_writer:
    kind: aws_wrangler_s3
    config:
      endpoint: http://localhost:9000
      database: blockchain
      use_boto3: true
      s3_path: s3://blockchain-data/aws-wrangler-s3
      region: "us-east-1"
      anchor_table: blocks
      partition_cols:
        blocks: [block_timestamp]
      default_partition_cols: [block_time]

pipelines:
  my_pipeline:
    provider:
      name: my_hypersync_provider
      config:
        url: "https://eth.hypersync.xyz"
        format: evm
        query:
          from_block: 20123123
          logs:
            - address: ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]
              event_signatures: ["Transfer(address indexed from, address indexed to, uint256 amount)"]           
          fields:
            block:
              number: true
            log:
              data: true
              topic0: true
              topic1: true
              topic2: true
              topic3: true
    
    steps:
      - name: get_last_block
        kind: get_last_block_number
        config:
        
      #- name: my_validate_evm_event
      #  kind: evm_validate_block_data (This part will fail)
      
      - name: decode_transfers
        kind: evm_decode_events
        config:
          event_signature: "Transfer(address,address,uint256)"
          input_table: "logs"
          output_table: "transfer_events"
          allow_decode_fail: true

    writer:
      name: my_aws_wrangler_s3_writer
      kind: aws_wrangler_s3
      config:
        endpoint: http://localhost:9000
        database: blockchain
        use_boto3: true
        s3_path: s3://blockchain-data/aws-wrangler-s3

